### ISSUE TITLE
Delay time differs from comment

### ISSUE THREAD

**Issue by gvenzl** [Seeed-Studio/Seeed_Python_DHT#1]
The comment says to wait for 20ms to collect 42 bytes of data while the code actually waits for 200ms (0.2 seconds) instead of (0.02 seconds). It is not clear whether this is a typo in the comment or a type in the code and perhaps should be doubled checked.

https://github.com/Seeed-Studio/Seeed_Python_DHT/blob/d4aa6700733431601fa9532afc51d9fad459a430/seeed_dht.py#L116-L121

**Comment by Pillar1989** [comment]
This should be a mistake in the commit
