### ISSUE TITLE
GrovePi Plus

### ISSUE THREAD

**Issue by WirthmU** [Seeed-Studio/Seeed_Python_DHT#2]
I would want the DHT22 sensor together with a GrovePi Plus hat. From what I have seen on the Seeed description it should be connected to the PWM port D4.

The configuration in the example python script says:

`sensor = seeed_dht.DHT(„22“, 4)`

Unfortunately temperature and humidity values remain at zero all the time.

Any help to this?

**Comment by Pillar1989** [comment]
Sorry, this software is not for GrovePi Hat, you can just do it with Grove Base Hat.

**Comment by WirthmU** [comment]
On https://wiki.seeedstudio.com/Grove-Temperature_and_Humidity_Sensor_Pro/ it says:

`Step 2. Connect Grove - Temperature&Humidity Sensor Pro to D4 port of GrovePi_Plus.`

So what software can I use?

**Comment by Pillar1989** [comment]
https://wiki.seeedstudio.com/Grove-Temperature_and_Humidity_Sensor_Pro/#software_2
